export const monthsList = [
  {
    id: 1,
    enum: 'JANUARY',
    title: 'January',
  },
  {
    id: 2,
    enum: 'FEBRUARY',
    title: 'February',
  },
  {
    id: 3,
    enum: 'MARCH',
    title: 'March',
  },
  {
    id: 4,
    enum: 'APRIL',
    title: 'April',
  },
  {
    id: 5,
    enum: 'MAY',
    title: 'May',
  },
  {
    id: 6,
    enum: 'JUNE',
    title: 'June',
  },
  {
    id: 7,
    enum: 'JULY',
    title: 'July',
  },
  {
    id: 8,
    enum: 'AUGUST',
    title: 'August',
  },
  {
    id: 9,
    enum: 'SEPTEMBER',
    title: 'September',
  },
  {
    id: 10,
    enum: 'OCTOBER',
    title: 'October',
  },
  {
    id: 11,
    enum: 'NOVEMBER',
    title: 'November',
  },
  {
    id: 12,
    enum: 'DECEMBER',
    title: 'December',
  },
]

export const daysList = [
  { id: 0, title: 1 },
  { id: 1, title: 2 },
  { id: 2, title: 3 },
  { id: 3, title: 4 },
  { id: 4, title: 5 },
  { id: 5, title: 6 },
  { id: 6, title: 7 },
  { id: 7, title: 8 },
  { id: 8, title: 9 },
  { id: 9, title: 10 },
  { id: 10, title: 11 },
  { id: 11, title: 12 },
  { id: 12, title: 13 },
  { id: 13, title: 14 },
  { id: 14, title: 15 },
  { id: 15, title: 16 },
  { id: 16, title: 17 },
  { id: 17, title: 18 },
  { id: 18, title: 19 },
  { id: 19, title: 20 },
  { id: 20, title: 21 },
  { id: 21, title: 22 },
  { id: 22, title: 23 },
  { id: 23, title: 24 },
  { id: 24, title: 25 },
  { id: 25, title: 26 },
  { id: 26, title: 27 },
  { id: 27, title: 28 },
  { id: 28, title: 29 },
  { id: 29, title: 30 },
  { id: 30, title: 31 },
]

const currentYear = new Date().getFullYear() - 10
const years = Array.from(
  { length: currentYear - 1950 + 1 },
  (_, i) => currentYear - i
)
const yearsData = years.map((year) => year.toString())

export const yearsList = []
yearsData.map((year, index) => {
  return yearsList.push({ id: index, title: year })
})

const countries = [
  {
    name: 'Afghanistan',
    phoneCode: '+93',
    alpha2code: 'AF',
    alpha3code: 'AFG',
    emoji: '🇦🇫',
  },
  {
    name: 'Albania',
    phoneCode: '+355',
    alpha2code: 'AL',
    alpha3code: 'ALB',
    emoji: '🇦🇱',
  },
  {
    name: 'Algeria',
    phoneCode: '+213',
    alpha2code: 'DZ',
    alpha3code: 'DZA',
    emoji: '🇩🇿',
  },
  {
    name: 'American Samoa',
    phoneCode: '+1',
    alpha2code: 'AS',
    alpha3code: 'ASM',
    emoji: '🇦🇸',
  },
  {
    name: 'Andorra',
    phoneCode: '+376',
    alpha2code: 'AD',
    alpha3code: 'AND',
    emoji: '🇦🇩',
  },
  {
    name: 'Angola',
    phoneCode: '+244',
    alpha2code: 'AO',
    alpha3code: 'AGO',
    emoji: '🇦🇴',
  },
  {
    name: 'Anguilla',
    phoneCode: '+1',
    alpha2code: 'AI',
    alpha3code: 'AIA',
    emoji: '🇦🇮',
  },
  {
    name: 'Antigua and Barbuda',
    phoneCode: '+1',
    alpha2code: 'AG',
    alpha3code: 'ATG',
    emoji: '🇦🇬',
  },
  {
    name: 'Argentina',
    phoneCode: '+54',
    alpha2code: 'AR',
    alpha3code: 'ARG',
    emoji: '🇦🇷',
  },
  {
    name: 'Armenia',
    phoneCode: '+374',
    alpha2code: 'AM',
    alpha3code: 'ARM',
    emoji: '🇦🇲',
  },
  {
    name: 'Aruba',
    phoneCode: '+297',
    alpha2code: 'AW',
    alpha3code: 'ABW',
    emoji: '🇦🇼',
  },
  {
    name: 'Australia',
    phoneCode: '+61',
    alpha2code: 'AU',
    alpha3code: 'AUS',
    emoji: '🇦🇺',
  },
  {
    name: 'Austria',
    phoneCode: '+43',
    alpha2code: 'AT',
    alpha3code: 'AUT',
    emoji: '🇦🇮',
  },
  {
    name: 'Azerbaijan',
    phoneCode: '+994',
    alpha2code: 'AZ',
    alpha3code: 'AZE',
    emoji: '🇦🇿',
  },
  {
    name: 'Bahrain',
    phoneCode: '+973',
    alpha2code: 'BH',
    alpha3code: 'BHR',
    emoji: '🇧🇭',
  },
  {
    name: 'Bangladesh',
    phoneCode: '+880',
    alpha2code: 'BD',
    alpha3code: 'BGD',
    emoji: '🇧🇩',
  },
  {
    name: 'Barbados',
    phoneCode: '+1',
    alpha2code: 'BB',
    alpha3code: 'BRB',
    emoji: '🇧🇧',
  },
  {
    name: 'Belarus',
    phoneCode: '+375',
    alpha2code: 'BY',
    alpha3code: 'BLR',
    emoji: '🇧🇾',
  },
  {
    name: 'Belgium',
    phoneCode: '+32',
    alpha2code: 'BE',
    alpha3code: 'BEL',
    emoji: '🇧🇪',
  },
  {
    name: 'Belize',
    phoneCode: '+501',
    alpha2code: 'BZ',
    alpha3code: 'BLZ',
    emoji: '🇧🇿',
  },
  {
    name: 'Benin',
    phoneCode: '+229',
    alpha2code: 'BJ',
    alpha3code: 'BEN',
    emoji: '🇧🇯',
  },
  {
    name: 'Bermuda',
    phoneCode: '+1',
    alpha2code: 'BM',
    alpha3code: 'BMU',
    emoji: '🇧🇲',
  },
  {
    name: 'Bhutan',
    phoneCode: '+975',
    alpha2code: 'BT',
    alpha3code: 'BTN',
    emoji: '🇧🇹',
  },
  {
    name: 'Bolivia',
    phoneCode: '+591',
    alpha2code: 'BO',
    alpha3code: 'BOL',
    emoji: '🇧🇴',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    phoneCode: '+599',
    alpha2code: 'BQ',
    alpha3code: 'BES',
    emoji: '🇧🇶',
  },
  {
    name: 'Bosnia and Herzegovina',
    phoneCode: '+387',
    alpha2code: 'BA',
    alpha3code: 'BIH',
    emoji: '🇧🇦',
  },
  {
    name: 'Botswana',
    phoneCode: '+267',
    alpha2code: 'BW',
    alpha3code: 'BWA',
    emoji: '🇧🇼',
  },
  {
    name: 'Brazil',
    phoneCode: '+55',
    alpha2code: 'BR',
    alpha3code: 'BRA',
    emoji: '🇧🇷',
  },
  {
    name: 'British Indian Ocean Territory',
    phoneCode: '+246',
    alpha2code: 'IO',
    alpha3code: 'IOT',
    emoji: '🇮🇴',
  },
  {
    name: 'British Virgin Islands',
    phoneCode: '+1',
    alpha2code: 'VG',
    alpha3code: 'VGB',
    emoji: '🇻🇬',
  },
  {
    name: 'Brunei Darussalam',
    phoneCode: '+673',
    alpha2code: 'BN',
    alpha3code: 'BRN',
    emoji: '🇧🇳',
  },
  {
    name: 'Bulgaria',
    phoneCode: '+359',
    alpha2code: 'BG',
    alpha3code: 'BGR',
    emoji: '🇧🇬',
  },
  {
    name: 'Burkina Faso',
    phoneCode: '+226',
    alpha2code: 'BF',
    alpha3code: 'BFA',
    emoji: '🇧🇫',
  },
  {
    name: 'Myanmar',
    phoneCode: '+95',
    alpha2code: 'MM',
    alpha3code: 'MMR',
    emoji: '🇲🇲',
  },
  {
    name: 'Burundi',
    phoneCode: '+257',
    alpha2code: 'BI',
    alpha3code: 'BDI',
    emoji: '🇧🇮',
  },
  {
    name: 'Cambodia',
    phoneCode: '+855',
    alpha2code: 'KH',
    alpha3code: 'KHM',
    emoji: '🇰🇭',
  },
  {
    name: 'Cameroon',
    phoneCode: '+237',
    alpha2code: 'CM',
    alpha3code: 'CMR',
    emoji: '🇨🇲',
  },
  {
    name: 'Canada',
    phoneCode: '+1',
    alpha2code: 'CA',
    alpha3code: 'CAN',
    emoji: '🇨🇦',
  },
  {
    name: 'Cabo Verde',
    phoneCode: '+238',
    alpha2code: 'CV',
    alpha3code: 'CPV',
    emoji: '🇨🇻',
  },
  {
    name: 'Cayman Islands',
    phoneCode: '+1',
    alpha2code: 'KY',
    alpha3code: 'CYM',
    emoji: '🇰🇾',
  },
  {
    name: 'Central African Republic',
    phoneCode: '+236',
    alpha2code: 'CF',
    alpha3code: 'CAF',
    emoji: '🇨🇫',
  },
  {
    name: 'Chad',
    phoneCode: '+235',
    alpha2code: 'TD',
    alpha3code: 'TCD',
    emoji: '🇮🇩',
  },
  {
    name: 'Chile',
    phoneCode: '+56',
    alpha2code: 'CL',
    alpha3code: 'CHL',
    emoji: '🇨🇱',
  },
  {
    name: 'China',
    phoneCode: '+86',
    alpha2code: 'CN',
    alpha3code: 'CHN',
    emoji: '🇨🇳',
  },
  {
    name: 'Colombia',
    phoneCode: '+57',
    alpha2code: 'CO',
    alpha3code: 'COL',
    emoji: '🇨🇴',
  },
  {
    name: 'Comoros',
    phoneCode: '+269',
    alpha2code: 'KM',
    alpha3code: 'COM',
    emoji: '🇰🇲',
  },
  {
    name: 'Cook Islands',
    phoneCode: '+682',
    alpha2code: 'CK',
    alpha3code: 'COK',
    emoji: '🇨🇰',
  },
  {
    name: 'Costa Rica',
    phoneCode: '+506',
    alpha2code: 'CR',
    alpha3code: 'CRI',
    emoji: '🇨🇷',
  },
  {
    name: 'Côte dIvoire',
    phoneCode: '+225',
    alpha2code: 'CI',
    alpha3code: 'CIV',
    emoji: '🇨🇮',
  },
  {
    name: 'Croatia',
    phoneCode: '+385',
    alpha2code: 'HR',
    alpha3code: 'HRV',
    emoji: '🇭🇷',
  },
  {
    name: 'Cuba',
    phoneCode: '+53',
    alpha2code: 'CU',
    alpha3code: 'CUB',
    emoji: '🇨🇺',
  },
  {
    name: 'Curaçao',
    phoneCode: '+599',
    alpha2code: 'CW',
    alpha3code: 'CUW',
    emoji: '🇨🇼',
  },
  {
    name: 'Cyprus',
    phoneCode: '+357',
    alpha2code: 'CY',
    alpha3code: 'CYP',
    emoji: '🇨🇾',
  },
  {
    name: 'Czechia',
    phoneCode: '+420',
    alpha2code: 'CZ',
    alpha3code: 'CZE',
    emoji: '🇨🇿',
  },
  {
    name: 'Denmark',
    phoneCode: '+45',
    alpha2code: 'DK',
    alpha3code: 'DNK',
    emoji: '🇩🇰',
  },
  {
    name: 'Djibouti',
    phoneCode: '+253',
    alpha2code: 'DJ',
    alpha3code: 'DJI',
    emoji: '🇩🇯',
  },
  {
    name: 'Dominica',
    phoneCode: '+1',
    alpha2code: 'DM',
    alpha3code: 'DMA',
    emoji: '🇩🇲',
  },
  {
    name: 'Dominican Republic',
    phoneCode: '+1',
    alpha2code: 'DO',
    alpha3code: 'DOM',
    emoji: '🇩🇴',
  },
  {
    name: 'Ecuador',
    phoneCode: '+593',
    alpha2code: 'EC',
    alpha3code: 'ECU',
    emoji: '🇪🇨',
  },
  {
    name: 'Egypt',
    phoneCode: '+20',
    alpha2code: 'EG',
    alpha3code: 'EGY',
    emoji: '🇪🇬',
  },
  {
    name: 'El Salvador',
    phoneCode: '+503',
    alpha2code: 'SV',
    alpha3code: 'SLV',
    emoji: '🇸🇻',
  },
  {
    name: 'Equatorial Guinea',
    phoneCode: '+240',
    alpha2code: 'GQ',
    alpha3code: 'GNQ',
    emoji: '🇬🇶',
  },
  {
    name: 'Eritrea',
    phoneCode: '+291',
    alpha2code: 'ER',
    alpha3code: 'ERI',
    emoji: '🇪🇷',
  },
  {
    name: 'Estonia',
    phoneCode: '+372',
    alpha2code: 'EE',
    alpha3code: 'EST',
    emoji: '🇪🇪',
  },
  {
    name: 'Ethiopia',
    phoneCode: '+251',
    alpha2code: 'ET',
    alpha3code: 'ETH',
    emoji: '🇪🇹',
  },
  {
    name: 'Falkland Islands',
    phoneCode: '+500',
    alpha2code: 'FK',
    alpha3code: 'FLK',
    emoji: '🇫🇰',
  },
  {
    name: 'Faroe Islands',
    phoneCode: '+298',
    alpha2code: 'FO',
    alpha3code: 'FRO',
    emoji: '🇫🇴',
  },
  {
    name: 'Federated States of Micronesia',
    phoneCode: '+691',
    alpha2code: 'FM',
    alpha3code: 'FSM',
    emoji: '🇫🇲',
  },
  {
    name: 'Fiji',
    phoneCode: '+679',
    alpha2code: 'FJ',
    alpha3code: 'FJI',
    emoji: '🇫🇯',
  },
  {
    name: 'Finland',
    phoneCode: '+358',
    alpha2code: 'FI',
    alpha3code: 'FIN',
    emoji: '🇫🇮',
  },
  {
    name: 'France',
    phoneCode: '+33',
    alpha2code: 'FR',
    alpha3code: 'FRA',
    emoji: '🇫🇷',
  },
  {
    name: 'French Guiana',
    phoneCode: '+594',
    alpha2code: 'GF',
    alpha3code: 'GUF',
    emoji: '🇬🇫',
  },
  {
    name: 'French Polynesia',
    phoneCode: '+689',
    alpha2code: 'PF',
    alpha3code: 'PYF',
    emoji: '🇵🇫',
  },
  {
    name: 'Gabon',
    phoneCode: '+241',
    alpha2code: 'GA',
    alpha3code: 'GAB',
    emoji: '🇬🇦',
  },
  {
    name: 'Georgia',
    phoneCode: '+995',
    alpha2code: 'GE',
    alpha3code: 'GEO',
    emoji: '🇬🇪',
  },
  {
    name: 'Germany',
    phoneCode: '+49',
    alpha2code: 'DE',
    alpha3code: 'DEU',
    emoji: '🇩🇪',
  },
  {
    name: 'Ghana',
    phoneCode: '+233',
    alpha2code: 'GH',
    alpha3code: 'GHA',
    emoji: '🇬🇭',
  },
  {
    name: 'Gibraltar',
    phoneCode: '+350',
    alpha2code: 'GI',
    alpha3code: 'GIB',
    emoji: '🇬🇮',
  },
  {
    name: 'Greece',
    phoneCode: '+30',
    alpha2code: 'GR',
    alpha3code: 'GRC',
    emoji: '🇬🇷',
  },
  {
    name: 'Greenland',
    phoneCode: '+299',
    alpha2code: 'GL',
    alpha3code: 'GRL',
    emoji: '🇬🇱',
  },
  {
    name: 'Grenada',
    phoneCode: '+1',
    alpha2code: 'GD',
    alpha3code: 'GRD',
    emoji: '🇬🇩',
  },
  {
    name: 'Guadeloupe',
    phoneCode: '+590',
    alpha2code: 'GP',
    alpha3code: 'GLP',
    emoji: '🇬🇵',
  },
  {
    name: 'Guam',
    phoneCode: '+1',
    alpha2code: 'GU',
    alpha3code: 'GUM',
    emoji: '🇬🇺',
  },
  {
    name: 'Guatemala',
    phoneCode: '+502',
    alpha2code: 'GT',
    alpha3code: 'GTM',
    emoji: '🇬🇹',
  },
  {
    name: 'Guinea',
    phoneCode: '+224',
    alpha2code: 'GN',
    alpha3code: 'GIN',
    emoji: '🇬🇳',
  },
  {
    name: 'Guinea-Bissau',
    phoneCode: '+245',
    alpha2code: 'GW',
    alpha3code: 'GNB',
    emoji: '🇬🇼',
  },
  {
    name: 'Guyana',
    phoneCode: '+592',
    alpha2code: 'GY',
    alpha3code: 'GUY',
    emoji: '🇬🇾',
  },
  {
    name: 'Haiti',
    phoneCode: '+509',
    alpha2code: 'HT',
    alpha3code: 'HTI',
    emoji: '🇭🇹',
  },
  {
    name: 'Honduras',
    phoneCode: '+504',
    alpha2code: 'HN',
    alpha3code: 'HND',
    emoji: '🇭🇳',
  },
  {
    name: 'Hong Kong',
    phoneCode: '+852',
    alpha2code: 'HK',
    alpha3code: 'HKG',
    emoji: '🇭🇰',
  },
  {
    name: 'Hungary',
    phoneCode: '+36',
    alpha2code: 'HU',
    alpha3code: 'HUN',
    emoji: '🇭🇺',
  },
  {
    name: 'Iceland',
    phoneCode: '+354',
    alpha2code: 'IS',
    alpha3code: 'ISL',
    emoji: '🇮🇸',
  },
  {
    name: 'India',
    phoneCode: '+91',
    alpha2code: 'IN',
    alpha3code: 'IND',
    emoji: '🇮🇳',
  },
  {
    name: 'Indonesia',
    phoneCode: '+62',
    alpha2code: 'ID',
    alpha3code: 'IDN',
    emoji: '🇮🇩',
  },
  {
    name: 'Iran',
    phoneCode: '+98',
    alpha2code: 'IR',
    alpha3code: 'IRN',
    emoji: '🇮🇷',
  },
  {
    name: 'Iraq',
    phoneCode: '+964',
    alpha2code: 'IQ',
    alpha3code: 'IRQ',
    emoji: '🇮🇶',
  },
  {
    name: 'Ireland',
    phoneCode: '+353',
    alpha2code: 'IE',
    alpha3code: 'IRL',
    emoji: '🇮🇪',
  },
  {
    name: 'Israel',
    phoneCode: '+972',
    alpha2code: 'IL',
    alpha3code: 'ISR',
    emoji: '🇮🇱',
  },
  {
    name: 'Italy',
    phoneCode: '+39',
    alpha2code: 'IT',
    alpha3code: 'ITA',
    emoji: '🇮🇹',
  },
  {
    name: 'Jamaica',
    phoneCode: '+1',
    alpha2code: 'JM',
    alpha3code: 'JAM',
    emoji: '🇯🇲',
  },
  {
    name: 'Japan',
    phoneCode: '+81',
    alpha2code: 'JP',
    alpha3code: 'JPN',
    emoji: '🇯🇵',
  },
  {
    name: 'Jordan',
    phoneCode: '+962',
    alpha2code: 'JO',
    alpha3code: 'JOR',
    emoji: '🇯🇴',
  },
  {
    name: 'Kazakhstan',
    phoneCode: '+7',
    alpha2code: 'KZ',
    alpha3code: 'KAZ',
    emoji: '🇰🇿',
  },
  {
    name: 'Kenya',
    phoneCode: '+254',
    alpha2code: 'KE',
    alpha3code: 'KEN',
    emoji: '🇰🇪',
  },
  {
    name: 'Kiribati',
    phoneCode: '+686',
    alpha2code: 'KI',
    alpha3code: 'KIR',
    emoji: '🇰🇮',
  },
  {
    name: 'Kosovo',
    phoneCode: '+383',
    alpha2code: 'XK',
    alpha3code: 'XXK',
    emoji: '🇽🇰',
  },
  {
    name: 'Kuwait',
    phoneCode: '+965',
    alpha2code: 'KW',
    alpha3code: 'KWT',
    emoji: '🇰🇼',
  },
  {
    name: 'Kyrgyzstan',
    phoneCode: '+996',
    alpha2code: 'KG',
    alpha3code: 'KGZ',
    emoji: '🇰🇬',
  },
  {
    name: 'Laos',
    phoneCode: '+856',
    alpha2code: 'LA',
    alpha3code: 'LAO',
    emoji: '🇱🇦',
  },
  {
    name: 'Latvia',
    phoneCode: '+371',
    alpha2code: 'LV',
    alpha3code: 'LVA',
    emoji: '🇱🇻',
  },
  {
    name: 'Lebanon',
    phoneCode: '+961',
    alpha2code: 'LB',
    alpha3code: 'LBN',
    emoji: '🇱🇧',
  },
  {
    name: 'Lesotho',
    phoneCode: '+266',
    alpha2code: 'LS',
    alpha3code: 'LSO',
    emoji: '🇱🇸',
  },
  {
    name: 'Liberia',
    phoneCode: '+231',
    alpha2code: 'LR',
    alpha3code: 'LBR',
    emoji: '🇱🇷',
  },
  {
    name: 'Libya',
    phoneCode: '+218',
    alpha2code: 'LY',
    alpha3code: 'LBY',
    emoji: '🇱🇾',
  },
  {
    name: 'Liechtenstein',
    phoneCode: '+423',
    alpha2code: 'LI',
    alpha3code: 'LIE',
    emoji: '🇱🇮',
  },
  {
    name: 'Lithuania',
    phoneCode: '+370',
    alpha2code: 'LT',
    alpha3code: 'LTU',
    emoji: '🇱🇹',
  },
  {
    name: 'Luxembourg',
    phoneCode: '+352',
    alpha2code: 'LU',
    alpha3code: 'LUX',
    emoji: '🇱🇺',
  },
  {
    name: 'Macao',
    phoneCode: '+853',
    alpha2code: 'MO',
    alpha3code: 'MAC',
    emoji: '🇲🇴',
  },
  {
    name: 'Macedonia',
    phoneCode: '+389',
    alpha2code: 'MK',
    alpha3code: 'MKD',
    emoji: '🇲🇰',
  },
  {
    name: 'Madagascar',
    phoneCode: '+261',
    alpha2code: 'MG',
    alpha3code: 'MDG',
    emoji: '🇲🇬',
  },
  {
    name: 'Malawi',
    phoneCode: '+265',
    alpha2code: 'MW',
    alpha3code: 'MWI',
    emoji: '🇲🇼',
  },
  {
    name: 'Malaysia',
    phoneCode: '+60',
    alpha2code: 'MY',
    alpha3code: 'MYS',
    emoji: '🇲🇾',
  },
  {
    name: 'Maldives',
    phoneCode: '+960',
    alpha2code: 'MV',
    alpha3code: 'MDV',
    emoji: '🇲🇻',
  },
  {
    name: 'Mali',
    phoneCode: '+223',
    alpha2code: 'ML',
    alpha3code: 'MLI',
    emoji: '🇲🇱',
  },
  {
    name: 'Malta',
    phoneCode: '+356',
    alpha2code: 'MT',
    alpha3code: 'MLT',
    emoji: '🇲🇹',
  },
  {
    name: 'Marshall Islands',
    phoneCode: '+692',
    alpha2code: 'MH',
    alpha3code: 'MHL',
    emoji: '🇲🇭',
  },
  {
    name: 'Martinique',
    phoneCode: '+596',
    alpha2code: 'MQ',
    alpha3code: 'MTQ',
    emoji: '🇲🇶',
  },
  {
    name: 'Mauritania',
    phoneCode: '+222',
    alpha2code: 'MR',
    alpha3code: 'MRT',
    emoji: '🇲🇷',
  },
  {
    name: 'Mauritius',
    phoneCode: '+230',
    alpha2code: 'MU',
    alpha3code: 'MUS',
    emoji: '🇲🇺',
  },
  {
    name: 'Mayotte',
    phoneCode: '+262',
    alpha2code: 'YT',
    alpha3code: 'MYT',
    emoji: '🇾🇹',
  },
  {
    name: 'Mexico',
    phoneCode: '+52',
    alpha2code: 'MX',
    alpha3code: 'MEX',
    emoji: '🇲🇽',
  },
  {
    name: 'Moldova',
    phoneCode: '+373',
    alpha2code: 'MD',
    alpha3code: 'MDA',
    emoji: '🇲🇩',
  },
  {
    name: 'Monaco',
    phoneCode: '+377',
    alpha2code: 'MC',
    alpha3code: 'MCO',
    emoji: '🇲🇨',
  },
  {
    name: 'Mongolia',
    phoneCode: '+976',
    alpha2code: 'MN',
    alpha3code: 'MNG',
    emoji: '🇲🇳',
  },
  {
    name: 'Montenegro',
    phoneCode: '+382',
    alpha2code: 'ME',
    alpha3code: 'MNE',
    emoji: '🇲🇪',
  },
  {
    name: 'Montserrat',
    phoneCode: '+1',
    alpha2code: 'MS',
    alpha3code: 'MSR',
    emoji: '🇲🇸',
  },
  {
    name: 'Morocco',
    phoneCode: '+212',
    alpha2code: 'MA',
    alpha3code: 'MAR',
    emoji: '🇲🇦',
  },
  {
    name: 'Mozambique',
    phoneCode: '+258',
    alpha2code: 'MZ',
    alpha3code: 'MOZ',
    emoji: '🇲🇿',
  },
  {
    name: 'Namibia',
    phoneCode: '+264',
    alpha2code: 'NA',
    alpha3code: 'NAM',
    emoji: '🇳🇦',
  },
  {
    name: 'Nauru',
    phoneCode: '+674',
    alpha2code: 'NR',
    alpha3code: 'NRU',
    emoji: '🇳🇷',
  },
  {
    name: 'Nepal',
    phoneCode: '+977',
    alpha2code: 'NP',
    alpha3code: 'NPL',
    emoji: '🇳🇵',
  },
  {
    name: 'Netherlands',
    phoneCode: '+31',
    alpha2code: 'NL',
    alpha3code: 'NLD',
    emoji: '🇳🇱',
  },
  {
    name: 'Netherlands Antilles',
    phoneCode: '+599',
    alpha2code: 'AN',
    alpha3code: 'ANT',
    emoji: '🇧🇶',
  },
  {
    name: 'New Caledonia',
    phoneCode: '+687',
    alpha2code: 'NC',
    alpha3code: 'NCL',
    emoji: '🇳🇨',
  },
  {
    name: 'New Zealand',
    phoneCode: '+64',
    alpha2code: 'NZ',
    alpha3code: 'NZL',
    emoji: '🇳🇿',
  },
  {
    name: 'Nicaragua',
    phoneCode: '+505',
    alpha2code: 'NI',
    alpha3code: 'NIC',
    emoji: '🇳🇮',
  },
  {
    name: 'Niger',
    phoneCode: '+227',
    alpha2code: 'NE',
    alpha3code: 'NER',
    emoji: '🇳🇪',
  },
  {
    name: 'Nigeria',
    phoneCode: '+234',
    alpha2code: 'NG',
    alpha3code: 'NGA',
    emoji: '🇳🇬',
  },
  {
    name: 'Niue',
    phoneCode: '+683',
    alpha2code: 'NU',
    alpha3code: 'NIU',
    emoji: '🇳🇺',
  },
  {
    name: 'Norfolk Island',
    phoneCode: '+672',
    alpha2code: 'NF',
    alpha3code: 'NFK',
    emoji: '🇳🇫',
  },
  {
    name: 'North Korea',
    phoneCode: '+850',
    alpha2code: 'KP',
    alpha3code: 'PRK',
    emoji: '🇰🇵',
  },
  {
    name: 'Northern Mariana Islands',
    phoneCode: '+1',
    alpha2code: 'MP',
    alpha3code: 'MNP',
    emoji: '🇲🇵',
  },
  {
    name: 'Norway',
    phoneCode: '+47',
    alpha2code: 'NO',
    alpha3code: 'NOR',
    emoji: '🇳🇴',
  },
  {
    name: 'Oman',
    phoneCode: '+968',
    alpha2code: 'OM',
    alpha3code: 'OMN',
    emoji: '🇴🇲',
  },
  {
    name: 'Pakistan',
    phoneCode: '+92',
    alpha2code: 'PK',
    alpha3code: 'PAK',
    emoji: '🇵🇰',
  },
  {
    name: 'Palau',
    phoneCode: '+680',
    alpha2code: 'PW',
    alpha3code: 'PLW',
    emoji: '🇵🇼',
  },
  {
    name: 'Palestine',
    phoneCode: '+970',
    alpha2code: 'PS',
    alpha3code: 'PSE',
    emoji: '🇵🇸',
  },
  {
    name: 'Panama',
    phoneCode: '+507',
    alpha2code: 'PA',
    alpha3code: 'PAN',
    emoji: '🇵🇦',
  },
  {
    name: 'Papua New Guinea',
    phoneCode: '+675',
    alpha2code: 'PG',
    alpha3code: 'PNG',
    emoji: '🇵🇬',
  },
  {
    name: 'Paraguay',
    phoneCode: '+595',
    alpha2code: 'PY',
    alpha3code: 'PRY',
    emoji: '🇵🇾',
  },
  {
    name: 'Peru',
    phoneCode: '+51',
    alpha2code: 'PE',
    alpha3code: 'PER',
    emoji: '🇵🇪',
  },
  {
    name: 'Philippines',
    phoneCode: '+63',
    alpha2code: 'PH',
    alpha3code: 'PHL',
    emoji: '🇵🇭',
  },
  {
    name: 'Poland',
    phoneCode: '+48',
    alpha2code: 'PL',
    alpha3code: 'POL',
    emoji: '🇵🇱',
  },
  {
    name: 'Portugal',
    phoneCode: '+351',
    alpha2code: 'PT',
    alpha3code: 'PRT',
    emoji: '🇵🇹',
  },
  {
    name: 'Puerto Rico',
    phoneCode: '+1',
    alpha2code: 'PR',
    alpha3code: 'PRI',
    emoji: '🇵🇷',
  },
  {
    name: 'Qatar',
    phoneCode: '+974',
    alpha2code: 'QA',
    alpha3code: 'QAT',
    emoji: '🇶🇦',
  },
  {
    name: 'Congo',
    phoneCode: '+242',
    alpha2code: 'CG',
    alpha3code: 'COG',
    emoji: '🇨🇬',
  },
  {
    name: 'Réunion',
    phoneCode: '+262',
    alpha2code: 'RE',
    alpha3code: 'REU',
    emoji: '🇷🇪',
  },
  {
    name: 'Romania',
    phoneCode: '+40',
    alpha2code: 'RO',
    alpha3code: 'ROU',
    emoji: '🇷🇴',
  },
  {
    name: 'Russia',
    phoneCode: '+7',
    alpha2code: 'RU',
    alpha3code: 'RUS',
    emoji: '🇷🇺',
  },
  {
    name: 'Rwanda',
    phoneCode: '+250',
    alpha2code: 'RW',
    alpha3code: 'RWA',
    emoji: '🇷🇼',
  },
  {
    name: 'Saint Barthélemy',
    phoneCode: '+590',
    alpha2code: 'BL',
    alpha3code: 'BLM',
    emoji: '🇧🇱',
  },
  {
    name: 'Saint Helena',
    phoneCode: '+290',
    alpha2code: 'SH',
    alpha3code: 'SHN',
    emoji: '🇸🇭',
  },
  {
    name: 'Saint Kitts and Nevis',
    phoneCode: '+1',
    alpha2code: 'KN',
    alpha3code: 'KNA',
    emoji: '🇰🇳',
  },
  {
    name: 'Saint Martin',
    phoneCode: '+590',
    alpha2code: 'MF',
    alpha3code: 'MAF',
    emoji: '🇲🇫',
  },
  {
    name: 'Saint Pierre and Miquelon',
    phoneCode: '+508',
    alpha2code: 'PM',
    alpha3code: 'SPM',
    emoji: '🇵🇲',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    phoneCode: '+1',
    alpha2code: 'VC',
    alpha3code: 'VCT',
    emoji: '🇻🇨',
  },
  {
    name: 'Samoa',
    phoneCode: '+685',
    alpha2code: 'WS',
    alpha3code: 'WSM',
    emoji: '🇼🇸',
  },
  {
    name: 'San Marino',
    phoneCode: '+378',
    alpha2code: 'SM',
    alpha3code: 'SMR',
    emoji: '🇸🇲',
  },
  {
    name: 'São Tomé and Príncipe',
    phoneCode: '+239',
    alpha2code: 'ST',
    alpha3code: 'STP',
    emoji: '🇸🇹',
  },
  {
    name: 'Saudi Arabia',
    phoneCode: '+966',
    alpha2code: 'SA',
    alpha3code: 'SAU',
    emoji: '🇸🇦',
  },
  {
    name: 'Senegal',
    phoneCode: '+221',
    alpha2code: 'SN',
    alpha3code: 'SEN',
    emoji: '🇸🇳',
  },
  {
    name: 'Serbia',
    phoneCode: '+381',
    alpha2code: 'RS',
    alpha3code: 'SRB',
    emoji: '🇷🇸',
  },
  {
    name: 'Seychelles',
    phoneCode: '+248',
    alpha2code: 'SC',
    alpha3code: 'SYC',
    emoji: '🇸🇨',
  },
  {
    name: 'Sierra Leone',
    phoneCode: '+232',
    alpha2code: 'SL',
    alpha3code: 'SLE',
    emoji: '🇸🇱',
  },
  {
    name: 'Singapore',
    phoneCode: '+65',
    alpha2code: 'SG',
    alpha3code: 'SGP',
    emoji: '🇸🇬',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    phoneCode: '+1',
    alpha2code: 'SX',
    alpha3code: 'SXM',
    emoji: '🇸🇽',
  },
  {
    name: 'Slovakia',
    phoneCode: '+421',
    alpha2code: 'SK',
    alpha3code: 'SVK',
    emoji: '🇸🇰',
  },
  {
    name: 'Slovenia',
    phoneCode: '+386',
    alpha2code: 'SI',
    alpha3code: 'SVN',
    emoji: '🇸🇮',
  },
  {
    name: 'Solomon Islands',
    phoneCode: '+677',
    alpha2code: 'SB',
    alpha3code: 'SLB',
    emoji: '🇸🇧',
  },
  {
    name: 'Somalia',
    phoneCode: '+252',
    alpha2code: 'SO',
    alpha3code: 'SOM',
    emoji: '🇸🇴',
  },
  {
    name: 'South Africa',
    phoneCode: '+27',
    alpha2code: 'ZA',
    alpha3code: 'ZAF',
    emoji: '🇿🇦',
  },
  {
    name: 'South Korea',
    phoneCode: '+82',
    alpha2code: 'KR',
    alpha3code: 'KOR',
    emoji: '🇰🇷',
  },
  {
    name: 'South Sudan',
    phoneCode: '+211',
    alpha2code: 'SS',
    alpha3code: 'SSD',
    emoji: '🇸🇸',
  },
  {
    name: 'Spain',
    phoneCode: '+34',
    alpha2code: 'ES',
    alpha3code: 'ESP',
    emoji: '🇪🇸',
  },
  {
    name: 'Sri Lanka',
    phoneCode: '+94',
    alpha2code: 'LK',
    alpha3code: 'LKA',
    emoji: '🇱🇰',
  },
  {
    name: 'Saint Lucia',
    phoneCode: '+1',
    alpha2code: 'LC',
    alpha3code: 'LCA',
    emoji: '🇱🇨',
  },
  {
    name: 'Sudan',
    phoneCode: '+249',
    alpha2code: 'SD',
    alpha3code: 'SDN',
    emoji: '🇸🇩',
  },
  {
    name: 'Suriname',
    phoneCode: '+597',
    alpha2code: 'SR',
    alpha3code: 'SUR',
    emoji: '🇸🇷',
  },
  {
    name: 'Swaziland',
    phoneCode: '+268',
    alpha2code: 'SZ',
    alpha3code: 'SWZ',
    emoji: '🇸🇿',
  },
  {
    name: 'Sweden',
    phoneCode: '+46',
    alpha2code: 'SE',
    alpha3code: 'SWE',
    emoji: '🇸🇪',
  },
  {
    name: 'Switzerland',
    phoneCode: '+41',
    alpha2code: 'CH',
    alpha3code: 'CHE',
    emoji: '🇨🇭',
  },
  {
    name: 'Syrian Arab Republic',
    phoneCode: '+963',
    alpha2code: 'SY',
    alpha3code: 'SYR',
    emoji: '🇸🇾',
  },
  {
    name: 'Taiwan',
    phoneCode: '+886',
    alpha2code: 'TW',
    alpha3code: 'TWN',
    emoji: '🇹🇼',
  },
  {
    name: 'Tajikistan',
    phoneCode: '+992',
    alpha2code: 'TJ',
    alpha3code: 'TJK',
    emoji: '🇹🇯',
  },
  {
    name: 'Tanzania',
    phoneCode: '+255',
    alpha2code: 'TZ',
    alpha3code: 'TZA',
    emoji: '🇹🇿',
  },
  {
    name: 'Thailand',
    phoneCode: '+66',
    alpha2code: 'TH',
    alpha3code: 'THA',
    emoji: '🇹🇭',
  },
  {
    name: 'Bahamas',
    phoneCode: '+1',
    alpha2code: 'BS',
    alpha3code: 'BHS',
    emoji: '🇧🇸',
  },
  {
    name: 'Gambia',
    phoneCode: '+220',
    alpha2code: 'GM',
    alpha3code: 'GMB',
    emoji: '🇬🇲',
  },
  {
    name: 'Timor-Leste',
    phoneCode: '+670',
    alpha2code: 'TL',
    alpha3code: 'TLS',
    emoji: '🇹🇱',
  },
  {
    name: 'Togo',
    phoneCode: '+228',
    alpha2code: 'TG',
    alpha3code: 'TGO',
    emoji: '🇹🇬',
  },
  {
    name: 'Tokelau',
    phoneCode: '+690',
    alpha2code: 'TK',
    alpha3code: 'TKL',
    emoji: '🇹🇰',
  },
  {
    name: 'Tonga',
    phoneCode: '+676',
    alpha2code: 'TO',
    alpha3code: 'TON',
    emoji: '🇹🇴',
  },
  {
    name: 'Trinidad and Tobago',
    phoneCode: '+1',
    alpha2code: 'TT',
    alpha3code: 'TTO',
    emoji: '🇹🇹',
  },
  {
    name: 'Tunisia',
    phoneCode: '+216',
    alpha2code: 'TN',
    alpha3code: 'TUN',
    emoji: '🇹🇳',
  },
  {
    name: 'Turkey',
    phoneCode: '+90',
    alpha2code: 'TR',
    alpha3code: 'TUR',
    emoji: '🇹🇷',
  },
  {
    name: 'Turkmenistan',
    phoneCode: '+993',
    alpha2code: 'TM',
    alpha3code: 'TKM',
    emoji: '🇹🇲',
  },
  {
    name: 'Turks and Caicos Islands',
    phoneCode: '+1',
    alpha2code: 'TC',
    alpha3code: 'TCA',
    emoji: '🇹🇨',
  },
  {
    name: 'Tuvalu',
    phoneCode: '+688',
    alpha2code: 'TV',
    alpha3code: 'TUV',
    emoji: '🇹🇻',
  },
  {
    name: 'Uganda',
    phoneCode: '+256',
    alpha2code: 'UG',
    alpha3code: 'UGA',
    emoji: '🇺🇬',
  },
  {
    name: 'Ukraine',
    phoneCode: '+380',
    alpha2code: 'UA',
    alpha3code: 'UKR',
    emoji: '🇺🇦',
  },
  {
    name: 'United Arab Emirates',
    phoneCode: '+971',
    alpha2code: 'AE',
    alpha3code: 'ARE',
    emoji: '🇦🇪',
  },
  {
    name: 'United Kingdom',
    phoneCode: '+44',
    alpha2code: 'GB',
    alpha3code: 'GBR',
    emoji: '🇬🇧',
  },
  {
    name: 'United States',
    phoneCode: '+1',
    alpha2code: 'US',
    alpha3code: 'USA',
    emoji: '🇺🇸',
  },
  {
    name: 'Uruguay',
    phoneCode: '+598',
    alpha2code: 'UY',
    alpha3code: 'URY',
    emoji: '🇺🇾',
  },
  {
    name: 'U.S. Virgin Islands',
    phoneCode: '+1',
    alpha2code: 'VI',
    alpha3code: 'VIR',
    emoji: '🇻🇮',
  },
  {
    name: 'Uzbekistan',
    phoneCode: '+998',
    alpha2code: 'UZ',
    alpha3code: 'UZB',
    emoji: '🇺🇿',
  },
  {
    name: 'Vanuatu',
    phoneCode: '+678',
    alpha2code: 'VU',
    alpha3code: 'VUT',
    emoji: '🇻🇺',
  },
  {
    name: 'Vatican City',
    phoneCode: '+39',
    alpha2code: 'VA',
    alpha3code: 'VAT',
    emoji: '🇻🇦',
  },
  {
    name: 'Venezuela',
    phoneCode: '+58',
    alpha2code: 'VE',
    alpha3code: 'VEN',
    emoji: '🇻🇪',
  },
  {
    name: 'Vietnam',
    phoneCode: '+84',
    alpha2code: 'VN',
    alpha3code: 'VNM',
    emoji: '🇻🇳',
  },
  {
    name: 'Wallis and Futuna',
    phoneCode: '+681',
    alpha2code: 'WF',
    alpha3code: 'WLF',
    emoji: '🇼🇫',
  },
  {
    name: 'Yemen',
    phoneCode: '+967',
    alpha2code: 'YE',
    alpha3code: 'YEM',
    emoji: '🇾🇪',
  },
  {
    name: 'Zambia',
    phoneCode: '+260',
    alpha2code: 'ZM',
    alpha3code: 'ZMB',
    emoji: '🇿🇲',
  },
  {
    name: 'Zimbabwe',
    phoneCode: '+263',
    alpha2code: 'ZW',
    alpha3code: 'ZWE',
    emoji: '🇿🇼',
  },
]

export const countryList = []
countries.map((country, index) => {
  return countryList.push({
    id: index,
    title: country.name + ' ' + country.emoji,
  })
})
